trigger:
- deploy

pool:
  vmImage: 'windows-2022'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  projectName: 'PrecioFishBoneVietnamASP.NETTraining'
  publishProfile: 'hieudang - Web Deploy'
  sqlScriptFileName: 'genMigrationCode'
steps:
- task: UseDotNet@2
  displayName: 'Install .NET 6 SDK'
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    performMultiLevelLookup: true

- task: PublishBuildArtifacts@1
  displayName: Publish publish profiles
  inputs:
    PathtoPublish: $(Build.SourcesDirectory)/$(projectName)/Properties/PublishProfiles/hieudang - Web Deploy.pubxml
    ArtifactName: PublishProfiles

- script: 'dotnet tool install --global dotnet-ef --version 6.0.0'
  displayName: Install EF Tool

# - script: 'dotnet ef database update --project $(Build.SourcesDirectory)/$(projectName)/$(projectName).csproj'
#   displayName: 'Update Database'

- script: 'dotnet ef migrations script --output $(Build.SourcesDirectory)/SQL/genMigrationCode.sql --idempotent --project $(Build.SourcesDirectory)/$(projectName)/$(projectName).csproj --context ItemContext'
  displayName: Create SQL Scripts
  
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: $(Build.SourcesDirectory)
    arguments: --configuration $(BuildConfiguration)
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    projects: $(Build.SourcesDirectory)
    arguments: --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)
    zipAfterPublish: True


- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  condition: succeededOrFailed()
  inputs:
    PathtoPublish: $(build.artifactstagingdirectory)
    TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: SQLScripts'
  inputs:
    PathtoPublish: $(Build.SourcesDirectory)/SQL/$(sqlScriptFileName).sql
    ArtifactName: SQLScripts
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)" /p:PublishProfile="$(publishProfile)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
