trigger:
- deploy

pool:
  vmImage: 'windows-2022'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  projectName: 'PrecioFishBoneVietnamASP.NETTraining'
  publishProfile: 'hieudang - Web Deploy'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET 6 SDK'
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    performMultiLevelLookup: true

- script: 'dotnet tool install --global dotnet-ef --version 6.0.0'
  displayName: Install EF Tool

- script: 'dotnet ef migrations add migrateDb --project $(Build.SourcesDirectory)/$(projectName)/$(projectName).csproj'
  displayName: 'Migration'

- script: 'dotnet ef database update migrateDb --project $(Build.SourcesDirectory)/$(projectName)/$(projectName).csproj'
  displayName: 'Update Database'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)" /p:PublishProfile="$(publishProfile)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
